version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ADD dev.sql /docker-entrypoint-initdb.d/
     # - ./db:/docker-entrypoint-initdb.d/
    restart: always
